### ISSUE TITLE
Data validation bug

### ISSUE THREAD

**Issue by mattdylan** [mattdylan/TDSPaster#27]
When pasting data that has a zero, empty data will be written to the tds file. 

I have narrowed the bug down to the data validation class.

**Comment by tylerc515** [comment]
Fixed the bug that was causing reading with a length of more than 4 chars (ie 0.123) to be written as blank readings. Moved the check for reading length to right after the trim. That way, if readingLength > 4 or < 1 AFTER TRIM, a blank reading is entered.
